# create CNV Plot from bed files

if(!interactive()) pdf(NULL)

library(data.table)
library(ggplot2)

color_selector <- function(x) {
    if (x > 0.1) {
        return("red")
    } else if (x < -0.1) {
       return("blue")
    } else {
       return("grey")
    }
}

# load input (reference and sample generated by bedtools coverage)
ref_path <- normalizePath(snakemake@input[["ref"]])
sample_path <- normalizePath(snakemake@input[["bed"]])

# ref_path <- "/mnt/nas/shared/targeted_bisulfite_data/CHIMAL001/cnv_files/CTRL_M1A_S230_binned_1M.bed"
# sample_path <- "/mnt/nas/shared/targeted_bisulfite_data/CHIMAL001/cnv_files/E_2024_1222_S90_binned_1M.bed"

beader <- c("chr", "start", "stop", "reads", "counts", "length", "coverage")
ref_bed <- fread(ref_path)
names(ref_bed) <- beader
sample_bed <- fread(sample_path)
names(sample_bed) <- beader

big_bed <- merge(sample_bed,
                 ref_bed,
                 by = c("chr", "start", "stop", "length"),
                 suffixes = c(".sample", ".ref"))

# to avoid dividing by zero
big_bed$reads.sample <- big_bed$reads.sample + 0.001
big_bed$reads.ref <- big_bed$reads.ref + 0.001

# (log2) fold change normalized by total number of reads
big_bed[, fc := ((reads.sample /median(reads.sample)) / (reads.ref / median(reads.ref)))]
#big_bed[, fc := ( (reads.sample / median(reads.sample[chr == .BY$chr])) / 
#                  (reads.ref    / median(reads.ref[chr == .BY$chr])) ), 
#        by = chr]

big_bed[, log2fc := log2(fc)]
big_bed$colorfc <- sapply(big_bed$log2fc, color_selector)

# remove non-standard chromosomes
big_bed <- big_bed[chr %in% paste0("chr", c(1:22, "X", "Y"))]
big_bed$chr <- factor(gsub("chr", "",big_bed$chr), levels = c(as.character(1:22), "X", "Y"))

# plot the CNV
ggplot(big_bed, aes(x = start, y = log2fc,  color = colorfc)) +
  geom_point(size=0.7) + 
  facet_grid(. ~ chr, switch="x", space = "free_x"  , scales = "free_x")+
  scale_x_continuous(breaks = NULL, labels = NULL, name="Chromosome")+
  theme(panel.border = element_rect(fill = "transparent", 
                                    color = "black", linewidth = 0.5),
        panel.spacing = unit(0, 'points'),
        panel.background = element_rect(fill = NA),
        strip.background = element_rect(colour = "black", fill = "white"),
        axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))+
  scale_color_manual(guide="none", values=c(red="red", blue="blue", grey="grey"))+
  geom_hline(yintercept=0)

# Save result
ggsave(paste0("cnv_plots/", snakemake@wildcards["sample"], "_CNV_profile.png"),
       width = 18, height = 9)
